version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pegasus
      MYSQL_DATABASE: pegasus
    command: --bind-address=0.0.0.0
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql: